name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        ./install
        source bin/activate
        python3 -m pip install --upgrade pip
        pip3 install pylint
    - name: Analysing the code with pylint
      run: |
        source bin/activate
        pylint $(git ls-files '*.py')
